### ISSUE TITLE
Don't insert 'commands' key when none are defined

### ISSUE THREAD

**Issue by agis-** [skroutz/cogy#18]
Right now, what we get is:

```yaml
---
cog_bundle_version: 4
name: foo
description: Cogy commands
version: '0.0.1'
commands: {} # <-- this
```
